apiVersion: apps/v1
kind: Deployment
metadata:
  name: csr-approver
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csr-approver

  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: csr-approver

    spec:
      serviceAccountName: csr-approver
      containers:
        - name: csr-approver
          image: deas/csr-approver:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          args:
            - -metrics-bind-address
            - ":8080"
            - -health-probe-bind-address
            - ":8081"
            - -leader-election

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081

          env:
            - name: PROVIDER_REGEX
              value: ^[abcdef]\.test\.ch$
            - name: PROVIDER_IP_PREFIXES
              value: "0.0.0.0/0,::/0"
            - name: MAX_EXPIRATION_SECONDS
              value: "31622400" # 366 days

      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
