{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "csr-approver.fullname" . }}
  namespace: {{ include "csr-approver.namespace" . }}
  labels:
    {{- include "csr-approver.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: '{{ .Values.metrics.port }}'
    prometheus.io/scrape: 'true'
  {{- with .Values.metrics.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.serviceType }}
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "csr-approver.selectorLabels" . | nindent 4 }}
{{- end }}
